version: "3"
services:
  app:
    build: ./containers/php
    volumes:
      - ./myapp:/work

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./myapp:/work
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./containers/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo

volumes:
  db-data:
