version: "3"
services:
  app:
    build: ./containers/php
    volumes:
      - ./myapp:/work

  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - ./myapp:/work

  db:
    build: ./containers/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    
  test-db:
    build: ./containers/mysql
    ports:
      - 3307:3306
    volumes:
      - test-db-store:/var/lib/mysql
    

volumes:
  db-store:
  test-db-store: