version: "3"
services:
  app:
    build: ./containers/php
    volumes:
      - ./myapp:/work

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./myapp:/work
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
