version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-fpm-buster
      - image: circleci/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:q1eDykcX9ZJOAcDlM50/1GC5vKAjea0Ww3suOhqogUo=
      - DB_CONNECTION: circle_test
      
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "myapp/composer.json" }}
            - v1-dependencies-

      - run:
          name: composer install
          working_directory: myapp
          command: composer install -n --prefer-dist
         
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "myapp/composer.json" }}    
      
      - run:
          name: php test
          working_directory: myapp
          command: vendor/bin/phpunit